\set ON_ERROR_STOP on
\getenv owner_password ED_DB_OWNER_PASSWORD
\getenv app_password ED_DB_APP_PASSWORD

CREATE ROLE ed_owner LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS PASSWORD :'owner_password';
CREATE ROLE ed_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS PASSWORD :'app_password';
ALTER DATABASE evidencedesk OWNER TO ed_owner;

-- Only bootstrap installs extensions; the runtime identity cannot change schema.
CREATE EXTENSION IF NOT EXISTS vector;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO ed_owner;
GRANT USAGE ON SCHEMA public TO ed_app;
GRANT CONNECT ON DATABASE evidencedesk TO ed_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ed_owner IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ed_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ed_owner IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ed_app;
